Implement API for claims repository (GDEV-1429)
ghga-de/auth-service pull request #22
Opened 2022-11-07 17:48 UTC by Cito

2022-11-09 11:05 UTC, KerstenBreuer requested changes
Just a few minor things.

Currently, the claims repository and user registry have no dedicated core module but the business logic is mostly contained within the fastapi routes. That should probably be changed in the later refactoring. I will leave a note.

2022-11-09 12:00 UTC, Cito commented on auth_service/user_management/user_registry/__init__.py
> +__version__ = "0.1.0"
Removed these individual version numbers for now. The Auth Adapter can still have its own version.

2022-11-09 12:16 UTC, Cito commented on auth_service/user_management/claims_repository/router.py
> +        claim = None
Changed in 0cec9e7.

2022-11-09 12:16 UTC, Cito commented on auth_service/user_management/claims_repository/router.py
> +        raise HTTPException(status_code=404, detail="The user claim was not found.")
Changed in 0cec9e7.

2022-11-09 12:18 UTC, Cito commented on auth_service/user_management/claims_repository/deps.py
> +    return await dao_factory.get_claim_dao()
Sollte zusammen mit dem Auslagern in ein Core-Modul gemacht werden.

2022-11-09 13:07 UTC, Cito commented
Thanks for the review, all good points. Readey for review again.

2022-11-11 13:11 UTC, KerstenBreuer commented on auth_service/user_management/user_registry/__init__.py
> +__version__ = "0.1.0"
The problem is that our production deployment will likely be triggered with a new release of the repository and there we can only have one version. However, we can figure that out in a different PR.

2022-11-11 13:11 UTC, KerstenBreuer approved these changes

2022-11-11 14:53 UTC, merged